# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0773bd6b72179529b489afd691d28d966a89a9820c907a851a265c79125fc0247c110dd5009aee3d12234f57840244fa8ddf23b9f754d43fc2a75eafc4264753

test:
  secret_key_base: cbb82fb27b62cf85bcbe4453c03a8e980147d43fc6ef465fc0d5b2e3a508640b1ce64467820e5e4cf0c40046bc2ab4ee6e5e52a0de1c8be0935ed428041693f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
