source 'https://rubygems.org'


gem 'rails', '5.0.0.1'
gem 'puma', '3.4.0'
gem 'sass-rails', '5.0.6'
gem 'uglifier', '3.0.0'
gem 'coffee-rails', '4.2.1'
gem 'jquery-rails', '4.1.1'
gem 'turbolinks', '5.0.1'
gem 'jbuilder', '2.4.1'

group :development, :test do
	gem 'sqlite3', '1.3.11'
	gem 'byebug', '9.0.0', platform: :mri
end

group :test do
	gem 'rails-controller-testing', '0.1.1'
	gem 'minitest-reporters',		'1.1.9'
	gem 'guard',					'2.13.0'
	gem 'guard-minitest',			'2.4.4'
end

group :production do
	gem 'pg', '0.18.4'
end

gem 'tzinfo-data', platform: [:mingw, :mswin, :x64_mingw, :jruby]